const assert=require('node:assert/strict'),P=require('../web/ride-parser.js');
const original={warmup:'5 minutes at 90 – 110 watts',main:'36 minutes total\n3 x 9 minute intervals for 27 minutes worth of work between 140 to 160 watts with 3 x 3 minutes spaced out inbetween',cooldown:'8 minutes ramping down from 160 to 80 watts'};
let x=P.parse(original,1,36);assert(!x.valid);assert(x.issues.some(s=>s.includes('watt target')));assert(!P.render(x).includes('id="manual-use-duration"'));
const fields={...original,main:'3 x 9 minutes at 140–160 watts with 3 minutes at 90–110 watts between intervals'};
x=P.parse(fields,1,36);assert.equal(x.minutes,46);assert(x.complete&&!x.valid&&x.mismatch);assert(P.render(x).includes('Use calculated total'));
x=P.parse(fields,1,46);assert(x.valid,x.issues.join('\n'));assert.equal(x.blocks.length,7);assert.deepEqual(x.blocks.filter(b=>b.section==='main').map(b=>b.minutes),[9,3,9,3,9]);assert.equal(x.blocks[0].watts,100);assert.equal(x.blocks[1].watts_low,140);assert.equal(x.blocks[1].watts_high,160);assert.equal(x.blocks.at(-1).from_watts,160);assert.equal(x.blocks.at(-1).to_watts,80);
assert(P.parse({...fields,main:'3 x (9 minutes at 140–160 watts + 3 minutes at 90–110 watts)'},1,49).valid);
assert(P.parse({...fields,main:'3 x 9 minutes at 150 watts with 3 x 3 minutes at 100 watts after each interval'},1,49).valid);
assert(!P.parse({...fields,main:'3 x 9 minutes at 150 watts with 3 x 3 minutes at 100 watts between intervals'},1,49).valid);
assert(!P.parse({...fields,main:'3 x 9 minutes at 150 watts with 4 x 3 minutes at 100 watts'},1).valid);
assert(P.parse({...fields,main:'3 x 9 minutes at 150 watts no recovery'},1,40).valid);
assert(P.parse({main:'1 minute at 100 W; 30 seconds at 120 W'},2,3).valid);
assert(!P.parse({main:'10 minutes at 200-100 watts'},1,10).valid);
assert(!P.parse({main:'3 x 9 minutes at 150 W and 5 minutes at 100 W no recovery'},1).valid);
assert(P.parse({...fields,main:'3 x 9 minute intervals for 27 minutes worth of work between 140 to 160 watts with 2 x 3 minutes at 90 to 110 watts inbetween'},1,46).valid);
assert(!P.parse({...fields,main:'3 x 9 minute intervals for 36 minutes worth of work between 140 to 160 watts with 2 x 3 minutes at 100 W inbetween'},1,46).valid);
assert(!P.parse({main:'10 minutes at 150 watts and 5 minutes at 90 watts'},1,15).valid);
x=P.parse({main:'10 minutes at 140-200 W'},1,10);assert(x.valid);assert.equal(x.warnings.length,1);
assert(!P.parse({main:'500 minutes at 100 W'},1,500).valid);
assert(!P.parse({main:'10 minutes at 100 W'},0,10).valid);
assert(!P.render(P.parse({main:'<script>alert(1)</script>'},1,10)).includes('<script>'));
console.log('PASS: watt bands, absolute ramps, recovery placement, time conflicts, repetitions, ambiguity and bounds');
