// Exercise the real page save handlers with isolated responses: never write athlete data.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('web/coach.html','utf8'),helpers=fs.readFileSync('web/checkin-ui.js','utf8');
function setup(){const elements={},posts=[],notices=[];const el=id=>elements[id]||(elements[id]={value:'',dataset:{},hidden:false,open:false,textContent:'',disabled:false,classList:{toggle(){}},addEventListener(){},close(){this.open=false;this.closed=true;},showModal(){this.open=true;},querySelectorAll(){return [];}});
 const context={document:{getElementById:el},Date,Math,console,setTimeout,day:{date:'2026-10-05',checkin:{}},checkinSaving:false,checkinRequest:null,shoulderTouched:false,editing:true,gut:null,$:el,esc:String,localStorage:{removeItem(){}},draftKey:()=>'',loadJournal:async()=>{},loadToday:async()=>{},post:async(u,b)=>{posts.push({u,b:structuredClone(b)});return context.reply(u,b);},fetch:async()=>({ok:true,json:async()=>({answered:{}})})};context.reply=()=>({ok:true,j:{}});vm.createContext(context);vm.runInContext(helpers,context);context.CheckinUI.thankYou=(...args)=>notices.push(args);return {context,el,posts,notices};}
function weekly(s,fields=[],daily=[]){const box=s.el('weeklycard');box.querySelectorAll=sel=>sel==='[data-wk]'?fields:sel==='[data-weekly-daily]'?daily:[];const start=html.indexOf('function weeklyToday(W)'),end=html.indexOf('let SWMIX=',start);vm.runInContext(html.slice(start,end),s.context);s.context.weeklyToday({sunday:'2026-10-04',week:['2026-09-28','2026-10-04'],questions:[{key:'week',label:'The week overall',scale:'1 easy, 10 too much'}],sports:[]});s.el('weeklydialog').open=true;return s.el('wksave').onclick;}
const rating=(key,value)=>({dataset:{wk:key},value:String(value),min:'1',max:'10'});
function daily(s){for(const k of ['legs','feet','breath','sleep'])s.el(k).value='3';s.el('journal').value='Real answers stay here';s.el('daily-dialog').open=true;const start=html.indexOf("$('send').onclick=async()=>{"),end=html.indexOf('// ── journal flags',start);vm.runInContext(html.slice(start,end),s.context);return s.el('send').onclick;}
(async()=>{
 let s=setup();assert.ok(s.context.CheckinUI.requestId());assert.equal(s.context.CheckinUI.hasWeeklyAnswer({sunday:'2026-10-04',lift:{},progress:{}}),false);
 let save=weekly(s,[],[{dataset:{weeklyDaily:'sleep'},value:'6'}]);await save();assert.equal(s.posts.length,0,'Empty weekly report must fail before daily write');assert.match(s.el('wkmsg').textContent,/at least one/);assert.equal(s.el('weeklydialog').open,true);
 s=setup();save=weekly(s,[rating('week',11)]);await save();assert.equal(s.posts.length,0);assert.match(s.el('wkmsg').textContent,/whole-number/);
 s=setup();save=weekly(s,[rating('week',4)],[{dataset:{weeklyDaily:'sleep'},value:'6'}]);await save();assert.equal(s.posts.length,3);assert.equal(s.posts[0].b.defer_refresh,true);assert.equal(s.notices[0][0],'weekly');assert.equal(s.el('weeklydialog').open,false);assert.equal(s.el('wksave').disabled,false);
 s=setup();save=weekly(s,[rating('week',4)],[{dataset:{weeklyDaily:'sleep'},value:'6'}]);s.context.reply=u=>({ok:!u.endsWith('/weekly'),j:{error:'Weekly service unavailable'}});await save();assert.equal(s.notices.length,0);assert.match(s.el('wkmsg').textContent,/Today’s readings are saved/);assert.equal(s.el('weeklydialog').open,true);const id=s.posts[0].b.request_id;await save();assert.equal(s.posts[2].b.request_id,id,'A retry must reuse daily journal request ID');
 s=setup();save=weekly(s,[rating('week',4)]);s.context.reply=()=>({ok:false,j:{error:'Review failed'}});s.context.fetch=async()=>({ok:true,json:async()=>({answered:{'2026-10-04':{week:4}}})});await save();assert.equal(s.notices[0][0],'weekly');assert.match(s.notices[0][1],/review did not finish/);
 s=setup();save=daily(s);s.context.reply=()=>({ok:false,j:{error:'Offline'}});await save();assert.equal(s.notices.length,0);assert.equal(s.el('daily-dialog').open,true);assert.equal(s.el('journal').value,'Real answers stay here');assert.equal(s.el('send').disabled,false);const dailyId=s.posts[0].b.request_id;s.context.reply=()=>({ok:true,j:{}});await save();assert.equal(s.posts[1].b.request_id,dailyId);assert.equal(s.notices[0][0],'daily');assert.equal(s.el('daily-dialog').open,false);assert.equal(s.el('feel').hidden,true);
 const history=s.context.CheckinUI.history({'2026-10-04':{week:4,note:'<img onerror=bad>'},'2026-09-27':{week:6},'2026-09-20':{legs:2}},'2026-10-04');assert.match(history,/Training response graphs/);assert.match(history,/&lt;img/);assert.doesNotMatch(history,/<img onerror/);assert.match(history,/October 2026/);assert.match(history,/September 2026/);assert.equal(s.context.CheckinUI.matchesWeekly({week:3},{sunday:'2026-10-04',week:4}),false);
 console.log('PASS: check-in validation, success, failure, partial save, retry deduplication, weekly history and safe rendering');
})().catch(e=>{console.error(e);process.exitCode=1;});
