/* Plan · load outlook: recorded and projected 3-day rate, biggest day and 28-day load against phase targets. Read-only. */
(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const energy=j=>EnergyUnits.text(j);
const axis=j=>EnergyUnits.unit==='calories'?Math.round(j/4184).toLocaleString():(j/1e6).toLocaleString(undefined,{maximumFractionDigits:2});
const PHASE={base:'Base',build:'Build',peak:'Peak',taper:'Taper',recovery:'Recovery',maintain:'Maintain'};
const COLOR={base:'#5aa7d6',build:'#e0a458',peak:'#e07a5f',taper:'#9b8bd6',recovery:'#5fc4a8',maintain:'#5aa7d6'};
function chart(o){
 const days=o.days,W=720,H=230,L=46,R=10,T=12,B=34,n=days.length,cap=o.typical_training_day_j*o.peak_cap;
 const top=Math.max(cap,...days.map(d=>Math.max(d.energy_j,d.rate3_j_per_day,d.target_rate3[1])))*1.08||1;
 const x=i=>L+(i+.5)*(W-L-R)/n,y=v=>T+(H-T-B)*(1-v/top),bw=Math.max(2,(W-L-R)/n*.62);
 const today=days.findIndex(d=>d.future)-1;
 const band=days.map((d,i)=>`<rect x="${x(i)-(W-L-R)/n/2}" y="${y(d.target_rate3[1])}" width="${(W-L-R)/n+.5}" height="${Math.max(1,y(d.target_rate3[0])-y(d.target_rate3[1]))}" fill="${COLOR[d.phase]||'#5aa7d6'}" opacity=".18"/>`).join('');
 const bars=days.map((d,i)=>d.energy_j?`<rect x="${x(i)-bw/2}" y="${y(d.energy_j)}" width="${bw}" height="${H-B-y(d.energy_j)}" rx="2" fill="${d.future?'url(#lo-hatch)':'#3d6f8f'}"><title>${esc(d.date)}: ${energy(d.energy_j)}${d.planned.length?' planned: '+d.planned.map(p=>esc(p.name||p.sport)+' '+energy(p.kcal*4184)).join(', '):''}</title></rect>`:'').join('');
 const line=(from,to,dash)=>{const pts=days.map((d,i)=>[i,d]).filter(([i])=>i>=from&&i<=to).map(([i,d])=>`${x(i).toFixed(1)},${y(d.rate3_j_per_day).toFixed(1)}`).join(' ');return pts?`<polyline points="${pts}" fill="none" stroke="#f3f7fa" stroke-width="2.2" ${dash?'stroke-dasharray="5 4" opacity=".8"':''}/>`:'';};
 const flags=days.map((d,i)=>d.flags.length?`<circle cx="${x(i)}" cy="${y(d.rate3_j_per_day)}" r="4.5" fill="#f0c78e"><title>${esc(d.date)}: ${esc(d.flags.join('; '))}</title></circle>`:'').join('');
 const ticks=[0,.5,1].map(f=>`<text x="${L-6}" y="${y(top/1.08*f)+4}" text-anchor="end">${axis(top/1.08*f)}</text><line x1="${L}" x2="${W-R}" y1="${y(top/1.08*f)}" y2="${y(top/1.08*f)}" stroke="#ffffff14"/>`).join('');
 const labels=days.map((d,i)=>(i===0||i===today||i===n-1||(i%7===0&&Math.abs(i-today)>2&&n-1-i>2))?`<text x="${x(i)}" y="${H-12}" text-anchor="middle">${esc(d.date.slice(5))}</text>`:'').join('');
 return `<svg class="lo-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Daily energy and 3-day rate, recorded and planned, against phase targets"><defs><pattern id="lo-hatch" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="6" height="6" fill="#3d6f8f55"/><line x1="0" y1="0" x2="0" y2="6" stroke="#8fc3e6" stroke-width="2"/></pattern></defs>${ticks}${band}${bars}<line x1="${L}" x2="${W-R}" y1="${y(cap)}" y2="${y(cap)}" stroke="#f0c78e" stroke-dasharray="3 5" opacity=".7"><title>Biggest-day guide: ${o.peak_cap}× your typical training day</title></line>${line(0,today,false)}${line(today,n-1,true)}${flags}${today>=0?`<line x1="${x(today)+((W-L-R)/n)/2}" x2="${x(today)+((W-L-R)/n)/2}" y1="${T}" y2="${H-B}" stroke="#ffffff55"/><text x="${x(today)+((W-L-R)/n)/2+4}" y="${T+10}">today</text>`:''}${labels}<text x="4" y="${T+8}">${EnergyUnits.unit==='calories'?'kcal':'MJ'}</text></svg>`;
}
async function render(){
 const host=document.getElementById('load-outlook');if(!host)return;
 let o;try{const r=await fetch('/api/coach/load-outlook?days=21',{cache:'no-store'});if(!r.ok)throw Error();o=await r.json();}catch(e){host.innerHTML='<h2>Load outlook</h2><p class="sub">Load outlook unavailable. Reopen the Hub to load it.</p>';return;}
 const now=o.days.find(d=>d.date===o.as_of)||o.days.at(-1),next=o.days.filter(d=>d.future).slice(0,7);
 const legend=Object.entries(PHASE).filter(([k])=>o.days.some(d=>d.phase===k)).map(([k,v])=>`<span><i style="background:${COLOR[k]}"></i>${v} target</span>`).join('');
 host.innerHTML=`<h2>Load outlook · next 3 weeks</h2><p class="sub">Your 3-day rate (line: solid recorded, dashed planned) and each day's energy (bars: solid recorded, hatched planned), against the phase's target band. Gold dots mark days the plan runs above target or stacks a big day. Read-only: change the plan to change the projection.</p>
 <div class="lo-now"><div><small>Phase today</small><b>${esc(PHASE[now.phase]||now.phase)}</b></div><div><small>3-day rate now</small><b>${energy(now.rate3_j_per_day)}/day</b><small>recorded so far · target ${energy(now.target_rate3[0])}–${energy(now.target_rate3[1])}/day${now.planned_today_j?`<br>with today's plan: ${energy(now.rate3_with_plan_j_per_day)}/day`:''}</small></div><div><small>Biggest day in the last 3</small><b>${energy(now.peak3.j)}</b><small>${esc(now.peak3.date)} · guide ${energy(o.typical_training_day_j*o.peak_cap)}</small></div><div><small>28-day load</small><b>${energy(now.load28_j)}</b></div></div>
 ${chart(o)}<div class="lo-legend">${legend}<span><i style="background:#f0c78e"></i>flag</span></div>
 <h3>Next 7 days</h3>${next.some(d=>d.flags.length)?`<ul class="lo-flags">${next.filter(d=>d.flags.length).map(d=>`<li><b>${esc(d.date)}</b> ${esc(d.flags.join('; '))}</li>`).join('')}</ul>`:''}<div class="wr-scroll"><table class="wr-ledger"><tr><th>Date</th><th>Phase</th><th>Planned</th><th>Projected 3-day rate</th><th>Target</th></tr>${next.map(d=>`<tr><td class="${d.flags.length?'wr-gap':''}">${esc(d.date)}${d.flags.length?' ⚑':''}</td><td>${esc(PHASE[d.phase]||d.phase)}</td><td>${d.planned.map(p=>`${esc(p.name||p.sport)} · ${energy(p.kcal*4184)} <small title="${esc(p.basis)}">ⓘ</small>`).join('<br>')||'Rest'}</td><td>${energy(d.rate3_j_per_day)}/day</td><td>${energy(d.target_rate3[0])}–${energy(d.target_rate3[1])}</td></tr>`).join('')}</table></div>
 <h3>Sessions that went well · last 90 days</h3>${(o.well_tolerated||[]).length?`<p class="sub">Reported as intended or easier, without pain of 3 or more. The planner reaches for these first to meet a target, then varies them.</p><ul class="lo-good">${o.well_tolerated.map(w=>`<li><b>${esc(w.name||w.sport)}</b> · ${w.times}× · last ${esc(w.last)}${w.at_rate3_j_per_day!=null?` · done at a 3-day rate of ${energy(w.at_rate3_j_per_day)}/day`:''}</li>`).join('')}</ul>`:'<p class="sub">No session reports yet. Report how sessions felt and the planner can reuse what works for you.</p>'}
 <details class="wr-details"><summary>How the targets are set</summary><p class="wr-note">Reference rate ${energy(o.reference_rate_j_per_day)}/day (${esc(o.reference_basis)}). Build step this week: ${Math.round(o.build_step.step*100)}% · ${esc(o.build_step.why)}.</p><p class="wr-note">${esc(o.basis)}</p></details>`;
}
window.LoadOutlook={render};
document.addEventListener('DOMContentLoaded',render);window.addEventListener('fitness-readings',render);window.addEventListener('energy-units-change',render);
})();
