/* Manual and MCP share the same preview/save transaction. No AI required. */
window.WatchImport=(()=>{
 const dialog=document.getElementById('watch-link-dialog'),body=document.getElementById('watch-link-body');
 let changed=async()=>{},queue=[],current=null,selection=null,busy=false;
 const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const title=s=>({bike:'Cycling',ride:'Cycling',swim:'Swimming',gym:'Strength / gym',run:'Running',walk:'Walking',other:'Other'})[s]||s;
 async function read(id){const r=await fetch('/api/coach/recording-links'+(id?'?activity_id='+encodeURIComponent(id):''));const j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Unable to read recording choices');return j;}
 function failure(e){body.innerHTML=`<p role="alert">${esc(e.message)}</p><p>Your imported files remain saved. Reopen this review to try again.</p>`;}
 async function choose(id){
  body.innerHTML='<p role="status">Reading workout choices…</p>';selection=null;
  try{current=await read(id);const a=current.activity;
   body.innerHTML=`<p><strong>${esc(title(a.sport))}</strong> · ${esc(a.date)} · ${esc(a.start.slice(11))} · ${esc(a.minutes)} min</p><p class="sub">Choose where this watch recording belongs. Suggestions use timestamps and duration; you confirm the match.</p>${current.current?'<p class="sub">This recording already has a saved choice. Saving again updates that choice.</p>':''}<section><h3>Scheduled workouts · ${esc(a.date)}</h3><div class="watch-link-choices">${current.scheduled.map((s,i)=>`<button type="button" data-scheduled="${i}"><b>${esc(s.name)}</b><span>${esc(s.minutes??'—')} min${s.already_linked?' · recording linked':''}</span></button>`).join('')||'<p class="sub">No scheduled workout of this sport on this date.</p>'}</div></section><section><h3>Recorded workouts</h3><div class="watch-link-choices">${current.recorded.map((s,i)=>`<button type="button" data-recorded="${i}"><b>${esc(s.name)}</b><span>${esc(s.source==='bridge'?'Bike recording':s.source==='linked'?'Linked recordings':'Watch recording')} · ${esc(s.start.slice(11))} · ${esc(s.minutes)} min${s.suggested?' · possible match':''}</span></button>`).join('')||'<p class="sub">No other recording of this sport on this date.</p>'}</div></section><button type="button" data-new>＋ New workout · ${esc(a.date)}</button><div id="watch-link-review" aria-live="polite"></div><p role="status" id="watch-link-status"></p>`;
  }catch(e){failure(e);}
 }
 function associationControls(){return `${selection.mode==='scheduled'&&current.recorded.length?`<label class="watch-link-offset">Another recording of this same session<select id="watch-link-recording"><option value="">Watch only</option>${current.recorded.map(a=>`<option value="${esc(a.id)}" ${selection.target_activity_id===a.id?'selected':''}>${esc(a.name)} · ${esc(a.start.slice(11))} · ${esc(a.source)}</option>`).join('')}</select></label><p class="sub">Select the bike recording here if it captured this same workout. Separate sessions stay separate.</p>`:''}${selection.mode==='activity'&&current.scheduled.length?`<label class="watch-link-offset">Scheduled workout (optional)<select id="watch-link-schedule"><option value="">Recording only</option>${current.scheduled.map(s=>`<option value="${s.session_index}" ${selection.session_index===s.session_index?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`:''}`;}
 function clockControl(){return selection?.target_activity_id?`<label class="watch-link-offset">Watch clock adjustment · seconds<input type="number" id="watch-link-offset" min="-86400" max="86400" step="1" value="${selection.offset_seconds||0}"></label><p class="sub">Default 0 uses the actual timestamps. Positive moves watch samples later; negative moves them earlier. Adjust only for a clock mismatch.</p>`:'';}
 async function preview(){
  if(!selection||busy)return;busy=true;const host=document.getElementById('watch-link-review');
  host.innerHTML='<p role="status">Preparing combined record…</p>';
  try{const r=await fetch('/api/coach/recording-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selection,save:false})});const j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Unable to preview');
   host.innerHTML=`<div class="card"><h3>Review ${selection.mode==='activity'?'linked recordings':selection.mode==='scheduled'?'completed scheduled workout':'new recorded workout'}</h3><p>${esc(title(j.workout.sport))} · ${esc(j.workout.date)} · ${esc(j.workout.minutes)} min</p><p class="sub">${esc(j.note)}</p>${associationControls()}<p>${Object.entries(j.measurements||{}).map(([k,v])=>`${esc(({avg_heart_rate:'Average HR',max_heart_rate:'Peak HR',avg_power:'Average power',avg_cadence:'Cadence'})[k])}: ${esc(Number(v).toFixed(1))} ${k.includes('heart')?'bpm':k.includes('power')?'W':'rpm'}`).join(' · ')}</p>${j.metric_sources?`<p>Power / cadence: ${esc(j.metric_sources.power)} · heart rate: ${esc(j.metric_sources.heart_rate)}</p>`:''}${j.alignment?`<p>${j.alignment.matched_hr_samples} of ${j.alignment.timeline_samples} timeline samples have watch heart rate within 2 seconds. Gaps remain blank.</p>`:''}${clockControl()}<button type="button" class="blue" data-save-link>Save ${selection.mode==='activity'?'linked workout':selection.mode==='scheduled'?'workout association':'new workout'}</button></div>`;
  }catch(e){host.innerHTML=`<p role="alert">${esc(e.message)}</p>${associationControls()}${clockControl()}`;}
  finally{busy=false;}
 }
 dialog.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b||busy)return;
  if(b.hasAttribute('data-choose-watch-files')){document.getElementById('importfiles').click();}
  else if(b.hasAttribute('data-scheduled')){const s=current.scheduled[+b.dataset.scheduled];selection={activity_id:current.activity.id,mode:'scheduled',date:s.date,session_index:s.session_index};const possible=current.recorded.filter(a=>a.suggested&&a.source==='bridge');if(possible.length===1)selection.target_activity_id=possible[0].id;await preview();}
  else if(b.hasAttribute('data-recorded')){const a=current.recorded[+b.dataset.recorded];selection={activity_id:current.activity.id,mode:'activity',target_activity_id:a.id,offset_seconds:current.current?.target_activity_id===a.id?current.current.offset_seconds:0};await preview();}
  else if(b.hasAttribute('data-new')){selection={activity_id:current.activity.id,mode:'new'};await preview();}
  else if(b.hasAttribute('data-open-watch'))await choose(b.dataset.openWatch);
  else if(b.hasAttribute('data-save-link')){
   busy=true;b.disabled=true;const status=document.getElementById('watch-link-status');status.textContent='Saving…';
   try{const r=await fetch('/api/coach/recording-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selection,save:true})});const j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Unable to save');await changed(j);queue=queue.filter(x=>x!==current.activity.id);if(queue.length){busy=false;await choose(queue[0]);}else{body.innerHTML='<p role="status">Saved. This workout is counted once, and the original recordings are retained.</p><button type="button" data-done>Done</button>';}}
   catch(err){status.textContent=err.message;b.disabled=false;}finally{busy=false;}
  }else if(b.hasAttribute('data-done'))dialog.close();
 });
 dialog.addEventListener('change',e=>{if(!selection)return;if(e.target.id==='watch-link-offset')selection.offset_seconds=+e.target.value;else if(e.target.id==='watch-link-recording'){if(e.target.value)selection.target_activity_id=e.target.value;else delete selection.target_activity_id;}else if(e.target.id==='watch-link-schedule'){if(e.target.value!==''){selection.session_index=+e.target.value;selection.date=current.activity.date;}else{delete selection.session_index;delete selection.date;}}else return;preview();});
 document.getElementById('watch-link-close').onclick=()=>dialog.close();
 async function open(ids=[]){queue=[...new Set(ids)];if(!dialog.open)dialog.showModal();if(queue.length)return choose(queue[0]);body.innerHTML='<p>Reading imported workouts…</p>';try{const j=await read();body.innerHTML=`<button type="button" class="blue" data-choose-watch-files>Choose watch files</button><p>Select an imported watch workout to review its association.</p><div class="watch-link-choices">${j.activities.map(a=>`<button type="button" data-open-watch="${esc(a.id)}"><b>${esc(title(a.sport))} · ${esc(a.date)}</b><span>${esc(a.start.slice(11))} · ${esc(a.minutes)} min${a.link?' · choice saved':''}</span></button>`).join('')||'<p>No watch recordings yet. Choose a FIT or TCX file first.</p>'}</div>`;}catch(e){failure(e);}}
 document.getElementById('review-watch-links').onclick=()=>open();
 return {open,configure:o=>{changed=o.changed||changed;}};
})();
