/* Presentation only: the Hub/MCP work_rate calculator owns every number. */
(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COLORS={bike:'#7dbcf3',run:'#ffab61',swim:'#4bdbde',gym:'#bb9df1',walk:'#e8cd7e',lift:'#f28fb5',impact:'#d9c27a'};
const ORDER=['run','walk','bike','swim','gym','lift','impact'];
const name=s=>({bike:'Cycling',run:'Running',swim:'Swimming',gym:'Gym',walk:'Walking',lift:'Lifting',impact:'Feet & bones'}[s]||s);
let data=null,request=null;
const format=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
function compact(n){return EnergyUnits.compact(n);}
function energyText(n){return EnergyUnits.text(n);}
function rateText(n){const q=EnergyUnits.rate(n);return q.equivalent==null?'not available':q.value+' '+q.unit+' <small class="wr-conversion">≈ '+q.equivalent+'</small>';}
function quantity(n,suffix){const rate=suffix==='min',q=rate?EnergyUnits.rate(n):compact(n),available=Number.isFinite(n)&&n>=0;
 const expanded=!available?'Not available':rate?q.value+' '+q.unit+' · '+q.equivalent:EnergyUnits.exact(n)+' per '+suffix;
 return `<div class="wr-value"><strong>${q.value}</strong><span class="wr-unit">${q.unit}${rate?'':`<small>/${suffix}</small>`}</span>${rate&&q.equivalent!=null?`<small class="wr-conversion">≈ ${q.equivalent}</small>`:''}</div><details class="wr-exact"><summary title="${expanded}">Expanded value ⌄</summary>${expanded} · estimated</details>`;}
async function read(){if(request)return request;request=fetch('/api/coach/work-rate',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Work-rate readings are unavailable. Reopen the Hub launcher to load the local experiment.');data=await r.json();return data;}).finally(()=>request=null);return request;}
async function refresh(container){try{const d=await read();if(container)card(container,d);return d;}catch(e){if(container){container.hidden=false;container.innerHTML=`<h2>Recorded work & response</h2><p class="wr-error" role="status">${esc(e.message)}</p>`;}return null;}}
function card(container,d){
 if(!container||!d)return;container.hidden=false;container.classList.add('work-rate-card');
 const mode=container.dataset.mode||'day',opened=new Set([...container.querySelectorAll('details[open][data-section]')].map(x=>x.dataset.section));
 const previousHistory=container.querySelector('[data-work-history]');
 const selectedDay=previousHistory?.dataset.selectedDay;
 const historyMetric=previousHistory?.dataset.metric||'energy',historyRange=previousHistory?.dataset.range||'28';
 const w=d.windows['3'],bg=d.windows['28'],c=w.cardio,l=w.lifting,suffix=mode==='minute'?'min':'day';
 const cn=mode==='minute'?c.j_per_min:(c.recorded_sessions?c.j_per_day:null),ln=mode==='minute'?l.j_per_min:(l.sessions?l.j_per_day:null);
 const rows=d.daily.slice(-3),regionRate=k=>rows.reduce((a,r)=>a+r.exposure[k],0)/3;
 const mix=Object.entries(c.share_percent).filter(([,v])=>v>0);
 const reports=d.reports||[],latest=reports[0];
 container.innerHTML=`<div class="wr-heading"><div><div class="wr-eyebrow">YOUR RECORDED TRAINING</div><h2>Recorded training</h2><div class="wr-note">${esc(w.start)} – ${esc(w.end)} · today is still in progress</div></div><span class="wr-local">Local experiment · <a href="/panel#energy-setting-title">Energy units</a></span></div>
 <div class="wr-modes" role="group" aria-label="Work-rate time basis"><button type="button" data-mode="minute" aria-pressed="${mode==='minute'}">During training</button><button type="button" data-mode="day" aria-pressed="${mode==='day'}">Across days</button></div>
 <div class="wr-numbers"><article class="wr-metric"><h3>Cardio · energy estimate</h3>${quantity(cn,suffix,true)}<div class="wr-caption">${mode==='minute'?(EnergyUnits.unit==='calories'?'Estimated energy rate · duration-weighted':'Estimated metabolic power · duration-weighted, not crank power'):'Energy per calendar day · includes days without recorded work'}<br>${c.known_sessions} of ${c.recorded_sessions} recorded sessions have an energy estimate${c.complete?'':' · partial coverage'}${sourceLine(c)}</div></article><div class="wr-plus" aria-hidden="true">+</div><article class="wr-metric wr-lift"><h3>Lifting · nominal work</h3>${quantity(ln,suffix)}<div class="wr-caption">${format(l.volume_lb)} lb moved over recorded repetitions<br>${l.sessions} logged sessions · ${l.excluded_sets} sets excluded from this estimate</div></article></div>
 <p class="wr-note">Cardio energy + nominal lifting work · separate estimates. Lifting is a mechanical energy equivalent, not calories burned.</p>
 <div class="wr-mix" aria-label="Share of known cardio energy by sport">${mix.map(([s,v])=>`<span style="width:${v}%;background:${COLORS[s]||'#a5b4c4'}" title="${esc(name(s))}: ${format(v)}%"></span>`).join('')}</div><div class="wr-legend">${mix.map(([s,v])=>`<span><i style="background:${COLORS[s]||'#a5b4c4'}"></i>${esc(name(s))} ${Math.round(v)}%</span>`).join('')}</div>
 <div class="wr-substats">${peakStat(c.peak_day,bg.cardio)}<div><small>Recent exposure · 28 days</small><b>${energyText(bg.cardio.known_j)}</b><small>Known energy · ${bg.cardio.known_sessions}/${bg.cardio.recorded_sessions} sessions${sourceLine(bg.cardio)}<br>Work recorded, not remaining fatigue</small></div><div><small>Lifting context · 28 days</small><b>${format(bg.lifting.volume_lb)} lb</b><small>Recorded dynamic repetition volume</small></div></div>
 <details class="wr-details" data-section="history"><summary>Work history</summary><div data-work-history></div></details>
 <details class="wr-details" data-section="sessions"><summary>Recorded sessions · by sport</summary><div data-sport-records></div></details>
 <details class="wr-details" data-section="reports"><summary>Your reported response · current and past</summary><p class="wr-note">Your check-ins describe how you felt. Workload contexts are shown alongside them; they do not prove which workout caused a symptom. Personal comfort bands have not been established.</p>${reports.slice(0,12).map(report).join('')||'<p class="wr-empty">No response reports in the last 90 days.</p>'}${reports.length>12?`<details><summary>Earlier reports (${reports.length-12})</summary>${reports.slice(12).map(report).join('')}</details>`:''}</details>
 <details class="wr-details" data-section="sources"><summary>Recorded sessions & calculation details</summary><p class="wr-note">${esc(d.basis.cardio)}</p><p class="wr-note">${esc(d.basis.lifting)}</p><p class="wr-note">${esc(d.basis.windows)}</p><div class="wr-scroll"><table class="wr-ledger"><thead><tr><th>Date</th><th>Session</th><th>Minutes</th><th>Energy · source</th></tr></thead><tbody>${d.activities.filter(a=>a.date>=w.start).map(a=>`<tr><td>${esc(a.date)}</td><td>${esc(name(a.sport))}</td><td>${format(a.minutes)}</td><td>${energyCell(a)}</td></tr>`).join('')}</tbody></table></div><h3>Recent lifting · up to 3 sessions in 10 days</h3><p class="wr-note">Duration-weighted rate: ${rateText(d.recent_lifts.j_per_min)} · nominal mechanical work. Holds and tempo do not change this calculation.</p>${d.recent_lifts.sessions.map(l=>`<details class="wr-report"><summary>${esc(l.date+' · '+l.session)} · ${format(l.volume_lb)} lb</summary><p>${esc(l.duration_basis)} · ${format(l.minutes)} min</p>${l.sets.map(s=>`<div>${esc(s.exercise)} · set ${s.set}: ${format(s.weight)} ${esc(s.unit)} × ${s.reps}</div>`).join('')}${l.excluded.length?`<p class="wr-note">Excluded: ${[...new Set(l.excluded.map(s=>s.exercise))].map(esc).join(', ')}. Static/unloaded work or unquantified resistance remains in the original workout.</p>`:''}</details>`).join('')}</details>`;

 container.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{container.dataset.mode=b.dataset.mode;card(container,d);});
 container.querySelectorAll('[data-section]').forEach(e=>e.open=opened.has(e.dataset.section));
 const historyTarget=container.querySelector('[data-work-history]');
 if(selectedDay)historyTarget.dataset.selectedDay=selectedDay;historyTarget.dataset.metric=historyMetric;historyTarget.dataset.range=historyRange;history(historyTarget,d);sessions(container.querySelector('[data-sport-records]'),d);container.querySelectorAll('[data-section]').forEach(e=>e.open=opened.has(e.dataset.section));
}
function sessions(container,d){
 if(!container)return;const groups=Object.groupBy?Object.groupBy(d.activities.filter(a=>a.source!=='lifts'),a=>a.sport):d.activities.filter(a=>a.source!=='lifts').reduce((o,a)=>{(o[a.sport]??=[]).push(a);return o;},{});
 container.innerHTML=Object.entries(groups).map(([sport,aa])=>`<details class="wr-report" data-section="sport:${esc(sport)}"><summary>${esc(name(sport))} · ${aa.length} recorded sessions</summary><div class="wr-scroll"><table class="wr-ledger"><tr><th>Date</th><th>Duration</th><th>Distance</th><th>Energy · source</th><th>Average HR</th></tr>${aa.slice().reverse().map(a=>`<tr><td>${esc(a.date)}</td><td>${format(a.minutes)} min</td><td>${a.km==null?'Not recorded':format(a.km)+' km'}</td><td>${energyCell(a)}</td><td>${a.avg_hr==null?'Not recorded':format(a.avg_hr)+' bpm'}</td></tr>`).join('')}</table></div></details>`).join('')||'<p>No sessions recorded.</p>';
}
function peakStat(p,c28){if(!p)return `<div><small>Biggest day · last 3 days</small><b>—</b><small>No recorded cardio in these 3 days</small></div>`;const q=compact(p.j),typ=c28.median_training_day_j,ratio=typ?p.j/typ:null;
 return `<div class="wr-peak"><small>Biggest day · last 3 days</small><b>${q.value} ${q.unit}</b><small>${esc(p.date)} · ${p.sports.map(s=>esc(name(s))).join(', ')}${ratio?`<br><strong class="${ratio>=1.5?'wr-hot':''}">${format(Math.round(ratio*10)/10)}× your typical training day</strong> (28-day median ${energyText(typ)}, over ${c28.training_days} days with work)`:''}</small></div>`;}
const SOURCE={power:'from power',motion:'from distance & gradient',watch:'watch estimate (heart-rate based)'};
function sourceLine(c){const s=Object.entries(c.sources||{});return s.length?'<br>'+s.map(([k,n])=>n+' '+esc(SOURCE[k]||k)).join(' · ')+((c.gaps||[]).length?` · ${c.gaps.length} with a watch gap`:''):'';}
function energyCell(a){if(a.energy_j==null)return 'Not recorded';const power=Number.isFinite(a.energy_power_w)?a.energy_power_w:Number.isFinite(a.minutes)&&a.minutes>0?a.energy_j/(a.minutes*60):null;
 const q=EnergyUnits.rate(power==null?null:power*60);
 const rate=q.equivalent!=null?`<div class="wr-session-power"><b>${q.value} ${q.unit}</b> <small class="wr-conversion">≈ ${q.equivalent}</small><small>${EnergyUnits.unit==='calories'?'Estimated energy rate':'Estimated metabolic power'}</small><details><summary>Rate calculation</summary><small>${esc(SOURCE[a.energy_source]||'Hub estimate')}. Energy ÷ session time. ${esc(a.duration_basis||'Recorded session duration')}; includes recorded rests. Not measured cycling power, a heart-rate zone or effort rating.</small></details></div>`:'';
 return `${energyText(a.energy_j)} <small>${esc(SOURCE[a.energy_source]||'')}${a.energy_source!=='watch'&&a.watch_energy_j!=null?` · watch ${energyText(a.watch_energy_j)}`:''}${a.energy_gap_ratio?` · <b class="wr-gap" title="Watch and primary estimate differ by more than 30%">gap ×${format(a.energy_gap_ratio)}</b>`:''}</small>${rate}`;}
function report(r){const c=r.context_3_days.cardio,q=compact(c.j_per_day),t=compact(r.context_28_days.cardio.known_j),basis={at_report:'frozen when saved',rebuilt:'rebuilt by back-fill',reconstructed:'reconstructed now · not yet frozen'}[r.context_basis||'reconstructed'];return `<article class="wr-report"><b>${esc(r.date)} · ${esc(r.kind)}</b><div>${Object.entries(r.readings).map(([k,v])=>`${esc(k.replaceAll('_',' '))}: ${esc(typeof v==='object'?JSON.stringify(v):v)}`).join(' · ')}</div><small>Recorded preceding 3-day energy rate: ${q.value} ${q.unit}/day · ${Object.entries(c.share_percent).map(([s,v])=>esc(name(s))+' '+Math.round(v)+'%').join(', ')||'no known energy'}${c.complete?'':' · partial'}${r.activity_id?' · linked workout '+esc(r.activity_id):''}${c.peak_day?`<br>Biggest day in those 3: ${energyText(c.peak_day.j)} (${esc(c.peak_day.date)})`:''}<br>Carried 28 days: ${t.value} ${t.unit}${r.context_3_days.session_load?.reports?` · session load ${format(r.context_3_days.session_load.srpe_au)} AU (3 days)`:''} · <i>${esc(basis)}</i></small></article>`;}
function value(day,key){if(key==='energy')return day.cardio.known_j;if(key==='lifting')return day.lifting.volume_lb;if(['engine','impact','muscle'].includes(key))return day.exposure[key];const r=day.regions[key];return Object.values(r?.sources||{}).reduce((a,v)=>a+(v||0),0);}
function readingText(n,key){return key==='energy'?energyText(n):format(n);}
// Each day's contributions by source, stacked: cardio by sport, leg muscles by sport, a region by every source.
function segments(day,key){let src={};if(key==='energy')src=day.cardio.sport_j||{};else if(key==='muscle')src=Object.fromEntries(Object.entries(day.sports||{}).map(([s,v])=>[s,v.muscle]));else if(day.regions?.[key])src=day.regions[key].sources;else return null;
 return Object.entries(src).filter(([,v])=>v>0).sort(([a],[b])=>(ORDER.indexOf(a)+99)%99-(ORDER.indexOf(b)+99)%99);}
function bar(day,metric,max){const total=value(day,metric),segs=segments(day,metric),h=Math.max(1,100*total/(max||1));
 if(!segs||!segs.length)return `<i style="height:${h}%;background:${metric==='lifting'?'#ffaf70':'#78c5f1'}"></i>`;
 return `<span class="wr-stack" style="height:${h}%">${segs.map(([s,v])=>`<i style="flex:${v};background:${COLORS[s]||'#a5b4c4'}${s==='impact'?';background-image:repeating-linear-gradient(45deg,#0003 0 3px,transparent 3px 6px)':''}"></i>`).join('')}</span>`;}
function stackLegend(rows,metric){const seen=[...new Set(rows.flatMap(day=>(segments(day,metric)||[]).map(([s])=>s)))].sort((a,b)=>(ORDER.indexOf(a)+99)%99-(ORDER.indexOf(b)+99)%99);return seen.length>1||seen.includes('impact')?`<div class="wr-legend">${seen.map(s=>`<span><i style="background:${COLORS[s]||'#a5b4c4'}"></i>${esc(s==='impact'?'Impact (bone & tendon)':name(s))}</span>`).join('')}</div>`:'';}
function history(container,d,key='energy',range='28',options={}){
 if(!container||!d)return;
 const controls=container.dataset.range||range,metric=container.dataset.metric||key;
 const cutoff=controls==='all'?d.history_start:new Date(Date.parse(d.as_of+'T12:00:00Z')-(Number(controls)-1)*86400000).toISOString().slice(0,10),rows=d.daily.filter(day=>day.date>=cutoff),max=Math.max(0,...rows.map(day=>value(day,metric)));
 container.innerHTML=`${options.controls===false?'':`<div class="wr-tools">${options.metricControls===false?'':`<button type="button" data-kind="energy" aria-pressed="${metric==='energy'}">Cardio</button><button type="button" data-kind="lifting" aria-pressed="${metric==='lifting'}">Lifting</button>`}${['28','90','all'].map(n=>`<button type="button" data-range="${n}" aria-pressed="${n===controls}">${n==='all'?'All history':n+' days'}</button>`).join('')}</div>`}<h3>${metric==='energy'?'Cardio energy · '+(EnergyUnits.unit==='calories'?'kcal/day':'J/day'):metric==='lifting'?'Lifting volume · lb/day':metric==='muscle'?'Leg muscles · work points/day':esc(d.daily.at(-1)?.regions[metric]?.name||'Recorded exposure')+' · work points/day'}</h3><p class="wr-note">Daily recorded work · today is in progress.</p><div class="wr-hist" aria-label="Daily recorded ${esc(metric)} histogram, stacked by source">${rows.map(day=>`<button type="button" data-day="${day.date}" title="${day.date}: ${readingText(value(day,metric),metric)}${(segments(day,metric)||[]).length>1?' · '+segments(day,metric).map(([s,v])=>name(s)+' '+readingText(v,metric)).join(', '):''}" aria-label="${day.date}: ${readingText(value(day,metric),metric)}">${bar(day,metric,max)}</button>`).join('')}</div><div class="wr-axis"><span>${rows[0]?.date||'No history'}</span><span>Peak ${readingText(max,metric)}</span><span>${d.as_of}</span></div>${stackLegend(rows,metric)}<p class="wr-reading" role="status">Tap or focus a day to read its recorded work and sources.</p><details><summary>Dated readings &amp; sources</summary><p class="wr-note">No record does not prove rest. Bars stack every source that day, by colour. Muscle points from each sport share one scale and add up; impact (bone & tendon loading from running) is a different tissue measure, drawn hatched on top. These are model points, not measured tissue forces.</p><div class="wr-scroll"><table class="wr-ledger"><tr><th>Date</th><th>Recorded value/day</th><th>Sources / coverage</th></tr>${rows.slice().reverse().map(day=>`<tr><td>${day.date}</td><td>${readingText(value(day,metric),metric)}</td><td>${esc(dayDetail(day,metric))}</td></tr>`).join('')}</table></div></details>`;
 container.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{container.dataset.metric=b.dataset.kind;history(container,d,key,range,options);});
 container.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{container.dataset.range=b.dataset.range;history(container,d,key,range,options);});
 container.querySelectorAll('[data-day]').forEach(b=>{const show=()=>{container.dataset.selectedDay=b.dataset.day;const day=rows.find(x=>x.date===b.dataset.day);container.querySelector('.wr-reading').textContent=day.date+' · '+readingText(value(day,metric),metric)+' per day · '+dayDetail(day,metric);};b.onclick=show;b.onfocus=show;});
 if(container.dataset.selectedDay)container.querySelector(`[data-day="${container.dataset.selectedDay}"]`)?.click();
}
function dayDetail(day,key){if(key==='energy')return day.cardio.known_sessions+'/'+day.cardio.recorded_sessions+' sessions with energy data'+(day.cardio.complete?'':' · partial');if(key==='lifting')return day.lifting.excluded_sets+' excluded sets';if(day.regions[key])return Object.entries(day.regions[key].sources).map(([s,v])=>name(s)+' '+format(v)).join(' · ')||'No exposure recorded';return Object.entries(day.sports).map(([s,v])=>name(s)+' '+format(v[key])).join(' · ')||'No exposure recorded';}
function regional(container,d,key='quads',options={}){
 if(!container||!d)return;container.dataset.metric=key;history(container,d,key,'28',options);
}
// Formatting archived snapshots does not revive the removed fatigue-score UI.
function historicalNumber(r){return r?.estimate?`${r.estimate.low.toFixed(1)}–${r.estimate.high.toFixed(1)}`:'—';}
window.WorkRate={read,refresh,card,history,regional,compact,energyText,rateText,historicalNumber,get data(){return data;}};
window.addEventListener('energy-units-change',()=>{const host=document.getElementById('work-rate-card');if(host&&data)card(host,data);});
})();
